version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  iotdb:
    image: apache/iotdb:1.2.2-node
    ports:
      - "6667:6667"
      - "31999:31999"
    environment:
      - IOTDB_USER=root
      - IOTDB_PASSWORD=root