spring:
  application:
    admin:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379

iotdb:
  node-urls:
  - "localhost:6667"
  username: root
  password: root
  max-size: 10

logging:
  level:
    root: debug
